<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Mapping;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllCustomers(string $order){

       return $this
            ->createQueryBuilder('customer')
            ->orderBy('customer.birthDate', ':sort')
            ->setParameter('sort', $order)
            ->getQuery()
            ->getResult();
    }




}
